### ISSUE TITLE
"Error: you must be authenticated to run this command", despite being authenticated

### ISSUE THREAD

**Issue by QuantumToasted** [cli/gh-webhook#11]
I'm trying to test webhook events locally, as this is my first time working with GH's webhooks. I've followed [this guide](https://docs.github.com/en/webhooks-and-events/webhooks/receiving-webhooks-with-the-github-cli) to set up `gh webhook` correctly, including adding the proper org scopes for my org [OpenFastDL](https://github.com/OpenFastDL). However, when I try to use `gh webhook forward`, I get the message `Error: you must be authenticated to run this command`.

The command I am attempting to run (maybe I'm doing something incorrect here?)
```
 gh webhook forward --org=OpenFastDL --events=issues,pull_request --url=https://localhost:44322/api/github/webhooks
 ```

Output of `gh auth status`:
```
> gh auth status
github.com
  ✓ Logged in to github.com as QuantumToasted (keyring)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: gho_************************************
  ✓ Token scopes: admin:org_hook, gist, read:org, repo, workflow
```

Output of `gh auth token`:
```
> gh auth token
gho_REDACTED
```

**Comment by QuantumToasted** [comment]
Upon further inspection, it seems https://github.com/cli/gh-webhook/blob/b8fb5686ed688da846f68eb2cc96f517d451712f/webhook/forward.go#L72-L75 isn't functioning as intended on my installation.

Following the rabbit hole led me to the `auth` module in the `go-gh` repo, specifically https://github.com/cli/go-gh/blob/026e976b60f91b35bd97a2d82914c24515dda127/pkg/auth/auth.go#L35-L52.

It tries to first read from $GITHUB_TOKEN or an appropriate config file(?), then it tries to effectively return the value of `gh auth token` by finding the path to `gh.exe`, by first using `$GH_PATH` then falling back to `safeexec.LookPath("gh")`. I don't know what safeexec does to find the location of the executable, but neither setting `$GH_PATH` nor letting it "find" the executable seems to function correctly in my circumstance. This is likely not an issue with `gh-webhook` specifically.

I was able to resolve this issue by setting the envvar `$GITHUB_TOKEN` and token lookup now works fine. If appropriate, feel free to transfer this issue to the correct repo

**Comment by stoe** [comment]
I think https://github.com/cli/gh-webhook/pull/9 will fix this. 

Just waiting on review.
